# Header
menu:
  Trang chủ: /
  Sự kiện: /events
  # Tutorials: https://www.youtube.com/channel/UCwczk9A3ITHTZT6W_9nalqg/playlists
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-119975443-1
gauges_analytics:
favicon: /images/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: